### ISSUE TITLE
Error: Cannot find module './build/Release/otapi' 

### ISSUE THREAD

**Issue by ben-haim** [PUREMoneySystems/otapi-js#1]
Hi There,  I got this issue any suggestion pls ?

module.js:340 
   throw err;

Error: Cannot find module './build/Release/otapi'
  at Function.Module._resolveFilename (module.js:338:15) 
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17) 
  at Object.<anonymous> (/root/dev/otapi-js/index.js:10:11) 
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32) 
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)

**Comment by ben-haim** [comment]
Any help ?
